adobe_analytics.settings:
  type: config_object
  label: 'Adobe Analytics settings'
  mapping:
    installation_mode:
      type: string
      label: 'Adobe analytics installation mode'
    cdn_install_type:
      type: string
      label: 'Adobe analytics installation type'
    development_s_code_config:
      type: string
      label: 'Development S code config path'
    production_s_code_config:
      type: string
      label: 'Production S code config path'
    development_s_code:
      type: string
      label: 'Development S code path'
    production_s_code:
      type: string
      label: 'Production S code path'
    development_footer_js_code:
      type: string
      label: 'Development Footer JS code'
    production_footer_js_code:
      type: string
      label: 'Production Footer JS code'
    development_cdn_custom_tracking_js_before:
      type: string
      label: 'Development Custom tracking JS code before'
    development_cdn_custom_tracking_js_after:
      type: string
      label: 'Development Custom tracking JS code after'
    production_cdn_custom_tracking_js_before:
      type: string
      label: 'Production Custom tracking JS code before'
    production_cdn_custom_tracking_js_after:
      type: string
      label: 'Production Custom tracking JS code after'
    development_tag_manager_container_path:
      type: string
      label: 'Development tag manager container path'
    production_tag_manager_container_path:
      type: string
      label: 'Production tag manager container path'
    development_tag_manager_footer_js:
      type: string
      label: 'Development Tag manager footer js code'
    production_tag_manager_footer_js:
      type: string
      label: 'Production Tag manager footer js code'
    role_tracking_type:
      type: string
      label: 'Role Tracking Type'
    js_file_location:
      type: string
      label: 'Javascript file location'
    codesnippet:
      type: string
      label: 'Codesnippet'
    version:
      type: string
      label: 'Version'
    image_file_location:
      type: string
      label: 'Image file location'
    token_cache_lifetime:
      type: integer
      label: 'Token cache lifetime'
    extra_variables:
      type: sequence
      label: 'Extra variables'
      sequence:
        type: adobe_analytics.variable
        label: 'Variable'
    track_roles:
      type: sequence
      label: 'Track roles'
      sequence:
        type: string
        label: 'Roles to track or not track'

adobe_analytics.data_layer:
  type: config_object
  label: 'Adobe Analytics data layer settings'
  mapping:
    data_layer_enabled:
      type: string
      label: 'Data layer enabled/disabled'
    data_layer_root_field:
      type: string
      label: 'Data layer root field'
    data_layer_json_object:
      type: string
      label: 'Data layer JSON string'
    role_tracking_type:
      type: string
      label: 'Role Tracking Type'
    track_roles:
      type: sequence
      label: 'Track roles'
      sequence:
        type: string
        label: 'Roles to track or not track'

adobe_analytics.data_layer_custom_javascript:
  type: config_object
  label: 'Adobe analytics data layer custom Javascript'
  mapping:
    data_layer_custom_javascript:
      type: string
      label: 'Adobe analytics data layer custom Javascript'
adobe_analytics.report_suite:
  type: config_object
  label: 'Adobe analytics Report Suite'
  mapping:
    mode:
      type: string
      label: 'Mode'
    development_report_suites:
      type: string
      label: 'Development report suites'
    production_report_suites:
      type: string
      label: 'Production report suites'
    development_domains:
      type: string
      label: 'Development domains'
    production_domains:
      type: string
      label: 'Production domains'
    site_section_prefix:
      type: string
      label: 'Site section prefix'
    site_section_delimiter:
      type: string
      label: 'Site section delimiter'
    page_name_base:
      type: string
      label: 'Page name base'
    page_name_prefix:
      type: string
      label: 'Page name prefix'
    page_name_delimiter:
      type: string
      label: 'Page name delimiter'
    page_name_homepage:
      type: string
      label: 'Page name homepage'
adobe_analytics.validation_config:
  type: config_object
  label: 'Adobe analytics form validator configuration'
  mapping:
    cloud_provider:
      type: string
      label: 'Provider for cloud domain'
    cloud_domain:
      type: string
      label: 'Validator pattern for cloud domain'
    tag_manager_provider:
      type: string
      label: 'Provider for tag manager'
    tag_manager_domain:
      type: string
      label: 'Validator pattern for tag manager'
adobe_analytics.variable:
  type: config_object
  label: 'Adobe Analytics variable'
  mapping:
    name:
      type: string
      label: 'Name'
    value:
      type: string
      label: 'Value'

field.value.adobe_analytics:
  type: mapping
  label: Default value
  mapping:
    include_custom_variables:
      type: boolean
      label: 'Include custom variables'
    include_main_codesnippet:
      type: boolean
      label: 'Include main code snippet'
    codesnippet:
      type: string
      label: 'Codesnippet'
