adoboanalystics.settings:
  type: config_object
  label: 'Adobe Analytics settings'
  mapping:
    adobeanalytics_role_tracking_type:
      type: string
      label: 'Role Tracking Type'
    adobeanalytics_js_file_location:
      type: string
      label: 'Javascript file location'
    adobeanalytics_codesnippet:
      type: string
      label: 'Codesnippet'
    adobeanalytics_version:
      type: string
      label: 'Version'
    adobeanalytics_image_file_location:
      type: string
      label: 'Image file location'
    adobeanalytics_token_cache_lifetime:
    adobeanalytics_extra_variables: { }
    adobeanalytics_track_roles: { }
    admin_only:
      type: boolean
      label: 'Only apply to admin pages'
