adobe_analytics.settings:
  type: config_object
  label: 'Adobe Analytics settings'
  mapping:
    role_tracking_type:
      type: string
      label: 'Role Tracking Type'
    js_file_location:
      type: string
      label: 'Javascript file location'
    codesnippet:
      type: string
      label: 'Codesnippet'
    version:
      type: string
      label: 'Version'
    image_file_location:
      type: string
      label: 'Image file location'
    token_cache_lifetime:
    extra_variables: { }
    track_roles: { }
    admin_only:
      type: boolean
      label: 'Only apply to admin pages'
