name: "Testing"
on:
  push:
    # This will make the workflow to not trigger on tags.
    branches:
      - "*"
jobs:
  drupal-coder:
    name: "Drupal Coder"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pfizer/edison_docker_base_testing/edison-testing:latest
      credentials:
        username: ${{ secrets.EDISON_GH_TESTING_USER }}
        password: ${{ secrets.EDISON_GH_TESTING_TOKEN }}
    steps:
      -
        name: "Checkout local repo"
        uses: actions/checkout@v3
      -
        name: "Run code sniffer for Drupal standards"
        run: robo --load-from /root/RoboFile.php phpcs:coder ${GITHUB_WORKSPACE}
  testing:
    name: "Automated tests"
    runs-on: ubuntu-latest
    # Edison Docker image where job executes in.
    container:
      image: ghcr.io/pfizer/edison_docker_base_testing/edison-testing:latest
      credentials:
        username: ${{ secrets.EDISON_GH_TESTING_USER }}
        password: ${{ secrets.EDISON_GH_TESTING_TOKEN }}
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: "site_db"
          MYSQL_USER: "drupal"
          MYSQL_PASSWORD: "password"
          MYSQL_ROOT_PASSWORD: "root_password"
    steps:
      -
        name: "Start httpd and php-fpm7 services"
        run: /usr/local/bin/httpd-foreground &
      -
        name: "Checkout local repo"
        uses: actions/checkout@v3
      -
        name: "Checkout Pfizer Edison GitHub Actions"
        uses: actions/checkout@v3
        with:
          repository: pfizer/edison_actions
          ref: "1.x"
          token: ${{ secrets.EDISON_GH_TESTING_TOKEN }}
          path: .github/actions/edison_actions
      -
        name: "Install site"
        id: install-site
        uses: ./.github/actions/edison_actions/actions/site-install
        with:
          repo-type: "module"
          packagist-token: ${{ secrets.EDISON_GH_TESTING_PACKAGIST_TOKEN }}
          default-edison-base-version: "dev-edn10057-8.x"
          default-skel-site-version: "dev-edn10057-9.x"
          default-skel-profile-version: ~4
      -
        name: "Run Edison verifications"
        uses: ./.github/actions/edison_actions/actions/edison-verifications
        with:
          site-root-dir: ${{ steps.install-site.outputs.site-root-dir }}
          site-url: ${{ steps.install-site.outputs.site-url }}
      -
        name: "Run code sniffer for php-compatibility"
        run: robo --load-from /root/RoboFile.php phpcs:php-compatibility  "${{ steps.install-site.outputs.site-root-dir }}/app/modules"
      -
        name: "Run Drupal check for deprecated code"
        run: robo --load-from /root/RoboFile.php drupal:check ${GITHUB_WORKSPACE}
      -
        name: "Run Drupal Unit tests"
        env:
          REPO_TYPE: "module"
        run: robo --load-from /root/RoboFile.php drupal:test --testsuite unit
      -
        name: "Run Drupal Kernel tests"
        env:
          REPO_TYPE: "module"
        run: robo --load-from /root/RoboFile.php drupal:test --testsuite kernel
      -
        name: "Run Drupal Functional tests"
        env:
          REPO_TYPE: "module"
        run: robo --load-from /root/RoboFile.php drupal:test --testsuite functional
